### ISSUE TITLE
"Could not get class storage for illuminate\support\facades\broadcast" when specifying a file path

### ISSUE THREAD

**Issue by brendt** [psalm/psalm-plugin-laravel#110]
If I run psalm with a file specified, the following error is thrown:

```
psalm app/Context/Product/Actions/UpdateProductComplianceCardAction.php
```

```
Scanning files...

   InvalidArgumentException

  Could not get class storage for illuminate\support\facades\broadcast

  at vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45
    41|     public function get($fq_classlike_name)
    42|     {
    43|         $fq_classlike_name_lc = strtolower($fq_classlike_name);
    44|         if (!isset(self::$storage[$fq_classlike_name_lc])) {
  > 45|             throw new \InvalidArgumentException('Could not get class storage for ' . $fq_classlike_name_lc);
    46|         }
    47|
    48|         return self::$storage[$fq_classlike_name_lc];
    49|     }
```

Running psalm on the whole codebase succeeds.

**Comment by JoeAlamo** [comment]
I have been experiencing this also, it has been very odd. It is for different facades at different times.

When I encounter the issue, if I re-run Psalm with `--no-diff` it runs all the way through without any issues.

**Comment by muglug** [comment]
What happens when you run `--debug-by-line`? The code it analyses should point to the root of the issue

**Comment by muglug** [comment]
If the plugin provides a return type for a given method, it’s assumed that any classes in that return type have already been scanned by Psalm.

A usual workaround for a magic method like `app` is to add for scanning all the possible classes it could return.

**Comment by mr-feek** [comment]
Anyone able to share some code that can reproduce?

**Comment by pdawson** [comment]
Just had this issue myself, what triggered it for me was hinting scopes on a model. 

It appears though it requires the FQCN rather than accepting `Builder` on its own:

**This works**
```
 * @method static self|Builder forCurrentDomain()
 * @method static self|Builder whereDomain(Domain|null $domain);
```

**This breaks it**:
```
 * @method static self|\Illuminate\Database\Eloquent\Builder forCurrentDomain()
 * @method static self|\Illuminate\Database\Eloquent\Builder whereDomain(Domain|null $domain);
```

---

```
> vendor/bin/psalm --show-info=true
Scanning files...

   InvalidArgumentException

  Could not get class storage for illuminate\support\facades\file

  at vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42
     38▕     public function get(string $fq_classlike_name): ClassLikeStorage
     39▕     {
     40▕         $fq_classlike_name_lc = strtolower($fq_classlike_name);
     41▕         if (!isset(self::$storage[$fq_classlike_name_lc])) {
  ➜  42▕             throw new \InvalidArgumentException('Could not get class storage for ' . $fq_classlike_name_lc);
     43▕         }
     44▕
     45▕         return self::$storage[$fq_classlike_name_lc];
     46▕     }
```

**Comment by ppmathis** [comment]
I've stumbled across the same issue while running Psalm against a Laravel project. Analyzing the whole code base works fine, but inspecting single files fails consistently with `Could not get class storage for <any facade class in Illuminate\Support\Facades>`. Unfortunately this results in the PhpStorm Psalm integration breaking, as the IDE will obviously head for analyzing single files instead of the whole code base whenever possible.

Given the request of @mr-feek, I was able to find a reproducer for this specific issue which consistently works on my system:

```shell
# PHP version
PHP 7.4.12 (cli) (built: Nov  1 2020 00:39:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

# Create empty Laravel v8.4.2 project
mkdir psalm-test
cd psalm-test
composer create-project --prefer-dist laravel/laravel=v8.4.2 .

# Integrate Psalm with Laravel plugin
composer require --dev vimeo/psalm=v4.2.1
./vendor/bin/psalm --init
composer require --dev psalm/plugin-laravel=v1.4.1
./vendor/bin/psalm-plugin enable psalm/plugin-laravel
```

Now create a new PHP file called `app/Reproducer.php` with the following contents:

```php
<?php

namespace App;

use Illuminate\Support\Facades\Validator;

class Reproducer {
	public function test(): void {
		Validator::make([], []);
	}
}
```

Running Psalm when no global scan has happened yet works flawlessly an unlimited amount of times, so `./vendor/bin/psalm app/Reproducer.php` can be run over and over without any influence. However as soon as at least one global scan happened the file-level scan fails every single time with the following message. This means that running...

```shell
# 1) Run global scan
./vendor/bin/psalm

# 2) Analyze only the reproducer file
./vendor/bin/psalm app/Reproducer.php
```

...will result in consistent failure:

```
Scanning files...

   InvalidArgumentException 

  Could not get class storage for illuminate\support\facades\auth

  at vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42
     38|     public function get(string $fq_classlike_name): ClassLikeStorage
     39|     {
     40|         $fq_classlike_name_lc = strtolower($fq_classlike_name);
     41|         if (!isset(self::$storage[$fq_classlike_name_lc])) {
 -> 42|             throw new \InvalidArgumentException('Could not get class storage for ' . $fq_classlike_name_lc);
     43|         }
     44| 
     45|         return self::$storage[$fq_classlike_name_lc];
     46|     }
```

The only way to get Psalm working again for this file is by running `./vendor/bin/psalm --clear-cache`, making the file-level scan work an unlimited times again until a global scan gets run which results in breakage again. This happens on all error levels in my tests and also for various similar versions of the reproducer class, e.g. when using the global helper `validator()` or DI to create the Validator instance.

**Comment by mr-feek** [comment]
I'm afraid this is outside my knowledge -- I think we need to defer to @muglug to help understand why psalm might be failing on subsequent scans

**Comment by salfum** [comment]
Have the same problem. Running with the `--no-cache` option helps, but it is not an option.

**Comment by mr-feek** [comment]
i've started digging through this again, and interestingly enough if we don't register stubs in this plugin, the error isn't reproducible. I'll keep digging as to _why_

**Comment by mr-feek** [comment]
I just pushed a [commit](https://github.com/psalm/psalm-plugin-laravel/commit/0d84139e1189dcb18e1c9cb5dd0c09a04b7c3d55) to force the scanning of `illuminate\support\facades\ratelimiter` and it fixes the case that @ppmathis kindfully put together.

This certainly is not a "longterm fix", but moreso a hack to get around the problem as I don't know how to fix the root cause.

Please provide any more cases that are currently failing that can be reproduced and I'll attempt to fix them.

**Comment by mr-feek** [comment]
I just pushed another fix -- https://github.com/psalm/psalm-plugin-laravel/commit/b287a0ad17f5086eb40fbc1c481768fe24588950 

I'm going to mark this issue as closed. Thank you for the reproducer @ppmathis , it was very helpful. If anyone else runs into a similar issue, please open a new issue with a reproducer so I can debug it
